#!/bin/bash
# Modifed By InsomNet4u
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to VPS-murah.net..."
sleep 0.1
echo "Checking Permision..."
sleep 0.2
echo -e "${green}Permission Accepted...${NC}"
sleep 3
echo""
echo "Modifed By InsomNet4u"
echo "Terimakasih sudah berlangganan InsomNet4u"
echo "===============================================";
echo " ";
if [ -e "/root/log-ban.txt" ]; then
echo "User yang diban oleh user-ban adalah";
echo "Waktu - Username - Jumlah Multilogin"
echo "-------------------------------------";
cat /root/log-ban.txt
else
echo " Tidak ada user yang melakukan pelanggaran"
echo " Atau"
echo " Script user-ban belum dijalankan"
fi
echo " ";
echo "===============================================";
echo "Terimakasih sudah berlanggan di InsomNet4u";
