#!/bin/bash
# Modifed By InsomNet4u
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to InsomNet4u..."
sleep 0.2
echo "Checking Permision..."
echo -e "${green}Permission Accepted...${NC}"
sleep 0.3
echo""
echo "Please Wait..."
sleep 0.5
echo "Generating Account..."
sleep 0.5
echo "Generating Host..."
sleep 0.5
echo "Generating Username..."
sleep 0.5
echo "Generating Password..."
sleep 1
MYIP=$(wget -qO- ipv4.icanhazip.com)
passrandom=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

username=trial
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo "Modifed By InsomNet4u"
  echo "Terimakasih sudah berlangganan di InsomNet4u"
  echo " "
  echo "Demikian Detail Account Trial Anda"
  echo "------------------------------"
  echo "   Host     : $MYIP" 
  echo "   Username : $username"
  echo "   Password : $passrandom"
  echo "   Port     : 22,80,109,143,443"
  echo "------------------------------"
  echo " "
  
else
  useradd trial
  usermod -s /bin/false trial
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$passrandom\n$passrandom" | passwd $username
  clear
  echo " "
  echo "Modifed By InsomNet4u"
  echo "Terimakasih sudah berlangganan InsomNet4u"
  echo " "
  echo "Demikian Detail Account Trial Anda"
  echo "------------------------------"
  echo "   Host     : $MYIP"
  echo "   Username : $username"
  echo "   Password : $passrandom"
  echo "   Port     : 22,80,109,143,443"
  echo "------------------------------"
  echo " "
fi